### ISSUE TITLE
Document power management

### ISSUE THREAD

**Issue by dbuentello** [tessel/t2-docs#110] opened 2016-09-04 00:46 UTC
There is sparse documentation dealing with power for both contributors & users. [This](https://forums.tessel.io/t/power-management-of-tessel-2/1630/2) was a good start. 

Questions a user might have:
Whats the power consumption of the tessel2?
Is there a low power mode?

Questions a contributor might have: 
How is power distributed? 

These are the ones that came to mind.

**Comment by dbuentello** [comment] 2016-09-04 00:54
Something like this would be end goal
Users: https://developer.mbed.org/cookbook/Power-Management
Contributor: https://developer.mbed.org/users/no2chem/notebook/mbed-power-controlconsumption/

**Comment by Frijol** [comment] 2016-09-06 15:20
duplicate of https://github.com/tessel/t2-docs/issues/4, @dbuentello want to add your comments to that issue & then I'll close this one?

**Comment by dbuentello** [comment] 2016-09-06 16:25
oops, guess I miss that. transferred notes. close at will.

**Comment by Frijol** [comment] 2016-09-06 18:59
👍

**Closed** 2016-09-06 18:59 UTC
